package it.polimi.ingsw.costanti;

/**
 * Class CharacterEffects is made of constant in which there are info about every character's card effect.
 */
public class CharacterEffects {
    public static final String MONK_EFFECT = Constants.ANSI_YELLOW+"MONK_EFFECT────>TAKE 1 STUDENT FROM THIS CARD AND "+
            "PLACE IT ON AN ISLAND OF YOUR CHOICE. THEN, DRAW A NEW STUDENT FROM THE BAG AND PLACE IT ON THIS CARD."+
            Constants.ANSI_RESET;
    public static final String INNKEEPER_EFFECT = Constants.ANSI_YELLOW+"INNKEEPER_EFFECT────>DURING THIS TURN, YOU TAKE"+
            " CONTROL OF ANY NUMBER OF PROFESSORS EVEN IF YOU HAVE THE NUMBER OF STUDENTS AS THE PLAYER WHO CURRENTLY "+
            "CONTROLS THEM."+Constants.ANSI_RESET;
    public static final String PRINCE_EFFECT = Constants.ANSI_YELLOW+"PRINCE_EFFECT────>CHOOSE AN ISLAND AND RESOLVE THE"+
            " ISLAND AS IF MOTHER NATURE HAD ENDED HER MOVEMENT THERE. MOTHER NATURE WILL STILL MOVE AND THE ISLAND "+
            "WHERE SHE ENDS HER MOVEMENT WILL ALSO BE RESOLVED."+Constants.ANSI_RESET;
    public static final String HERALD_EFFECT = Constants.ANSI_YELLOW+"HERALD_EFFECT────>YOU MAY MOVE MOTHER NATURE UP TO"+
            "2 ADDITIONAL ISLANDS THAN IS INDICATED BY THE ASSISTANT CARD YOU'VE PLAYED."+Constants.ANSI_RESET;
    public static final String GROCER_EFFECT = Constants.ANSI_YELLOW+"GROCER_EFFECT────>PLACE A \"NO ENTRY\" TILE ON AN"+
            " ISLAND OF YOUR CHOICE. THE FIRST TIME MOTHER NATURE ENDS HER MOVEMENT THERE, PUT THE \"NO ENTRY\" TILE "+
            "ONTO THIS CARD AND"+Constants.ANSI_RESET+Constants.ANSI_RED+"DO NOT CALCULATE"+Constants.ANSI_RESET+
            Constants.ANSI_YELLOW+"INFLUENCE ON THAT ISLAND, OR PLACE ANY TOWERS."+Constants.ANSI_RESET;
    public static final String CENTAUR_EFFECT = Constants.ANSI_YELLOW+"CENTAUR_EFFECT────>WHEN RESOLVING A CONQUERING "+
            "ON AN ISLAND, TOWERS DO NOT COUNT TOWARDS INFLUENCE."+Constants.ANSI_RESET;
    public static final String JESTER_EFFECT = Constants.ANSI_YELLOW+"JESTER_EFFECT────>YOU MAY TAKE UP TO 3 STUDENTS "+
            "FROM THIS CARD AND REPLACE THEM WITH THE SAME NUMBER OF STUDENTS FROM YOUR ENTRANCE."+Constants.ANSI_RESET;
    public static final String KNIGHT_EFFECT = Constants.ANSI_YELLOW+"KNIGHT_EFFECT────>DURING THE INFLUENCE CALCULATION"+
            "THIS TURN, YOU COUNT AS HAVING 2 MORE INFLUENCE."+Constants.ANSI_RESET;
    public static final String MERCHANT_EFFECT = Constants.ANSI_YELLOW+"MERCHANT_EFFECT────>CHOOSE A COLOR OF STUDENT: "+
            "DURING THE INFLUENCE CALCULATION OF CURRENT TURN, THAT COLOR ADDS NO INFLUENCE."+Constants.ANSI_RESET;
    public static final String MINSTREL_EFFECT = Constants.ANSI_YELLOW+"MINSTREL_EFFECT────>YOU MAY EXCHANGE UP TO 2 "+
            "STUDENTS BETWEEN YOUR ENTRANCE AND YOUR DINING ROOM."+Constants.ANSI_RESET;
    public static final String WARRIOR_PRINCESS_EFFECT = Constants.ANSI_YELLOW+"WARRIOR_PRINCESS_EFFECT────>TAKE 1 " +
            "STUDENT FROM THIS CARD AND PLACE IT IN YOUR DINING ROOM. THEN, DRAW A NEW STUDENT FROM THE BAG AND PLACE "+
            "IT ON THIS CARD."+Constants.ANSI_RESET;
    public static final String THIEF_EFFECT = Constants.ANSI_YELLOW+"THIEF_EFFECT────>CHOOSE A TYPE OF STUDENT: EVERY "+
            "PLAYER (INCLUDING YOURSELF) MUST RETURN 3 STUDENTS OF THAT TYPE FROM THEIR DINING ROOM  TO THE BAG. IF ANY"+
            "PLAYER HAS FEWER THAN 3 STUDENTS OF THAT TYPE, RETURN AS MANY STUDENTS AS THEY HAVE."+Constants.ANSI_RESET;

}
